<?php


namespace PlusForta\PostmarkBundle\Tests;


use PlusForta\PostmarkBundle\PlusFortaPostmarkBundle;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\BundleInterface;
use Symfony\Component\HttpKernel\Kernel;

class PostmarkTestingKernel extends Kernel
{
    /**
     * @var array
     */
    private $postmarkClientConfig;

    public function __construct(array $postmarkClientConfig = [])
    {
        $this->postmarkClientConfig = $postmarkClientConfig;

        parent::__construct('test', true);
    }


    /**
     * Returns an array of bundles to register.
     *
     * @return iterable|BundleInterface[] An iterable of bundle instances
     */
    public function registerBundles()
    {
        return [
            new PlusFortaPostmarkBundle()
        ];
    }

    /**
     * Loads the container configuration.
     */
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(function (ContainerBuilder $container) {
            $container->loadFromExtension('plusforta_postmark', $this->postmarkClientConfig);
        });
    }

    public function getCacheDir()
    {
        return parent::getCacheDir() . '/' . spl_object_hash($this); // TODO: Change the autogenerated stub
    }
}